### PR TITLE
Added CSS RTL Support.

### PR DESCRIPTION
**Pull request by KingYes**
Hey justintadlock,
I just add new support for RTL support..

Thanks you for your good code. :)

Yakir.

### CODE REVIEW

**Comment by justintadlock** [comment]
I'm thinking about taking this a different direction and using the WordPress-generated "rtl" body class.  It'll simplify the code and we won't need any additional files or PHP.

**Comment by KingYes** [comment]
No Problem.

**Comment by justintadlock** [comment]
https://github.com/justintadlock/grid-columns/commit/8d1e7431606fbc1de291917f3ab76b580346a2bf

I just committed a first-pass on RTL styles on the 0.2 branch.  I don't really have a testing environment set up for this.  Whenever you get a chance, let me know if it works for you.

Also, this code assumes that your WordPress theme correctly uses the body_class() function (most do).

**Comment by KingYes** [comment]
You can copy&paste my css code from here:
https://github.com/KingYes/grid-columns/blob/master/css/columns-rtl.css

**Comment by justintadlock** [comment]
I'm marking this as resolved.  Everything seems to be in order in my tests.  If anyone runs into any issues with it, let me know.

**Pull request closed without merging**
